use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct User {
    pub name: String,
    /// Argon2id PHC string, e.g.
    /// `$argon2id$v=19$m=5120,t=2,p=1$<salt>$<hash>`. Self-contained:
    /// algorithm, parameters, per-user salt, and digest are all encoded
    /// inline. Generated by `auth::compute_hash`, verified by
    /// `auth::AuthState::verify`.
    pub hash: String,
    /// When `false`, this user is rejected on auth without revealing the
    /// distinction between disabled and unknown.
    #[serde(default = "default_true")]
    pub is_enabled: bool,
    /// When `true`, traffic for this user bypasses the upstream proxy pool
    /// and goes directly from this server's IP.
    #[serde(default)]
    pub direct: bool,
}

fn default_true() -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_direct_field_defaults_to_false() {
        let src = "\
name: alice
hash: $argon2id$v=19$m=5120,t=2,p=1$abc$def
is_enabled: true
";
        let user: User = ktav::from_str(src).unwrap();
        assert_eq!(user.name, "alice");
        assert!(!user.direct);
    }
}
